const content = {
  pt: {
    skip:'Pular para o conteúdo', nav:{about:'Sobre',projects:'Projetos',journey:'Jornada',skills:'Skills',contact:'Contato'},
    hero:{availability:'Disponível para oportunidades',eyebrow:'01 — PORTFÓLIO / 2026',title:'Construindo experiências digitais <em>claras</em> e funcionais.',copy:'Sou Carlos Renato, desenvolvedor em formação. Transformo ideias e necessidades reais em interfaces que fazem sentido para as pessoas.',projects:'Explorar projetos',email:'Vamos conversar',scroll:'Role para descobrir'},
    about:{eyebrow:'SOBRE MIM',title:'Código com intenção.<br /><em>Aprendizado</em> em movimento.',caption:'Meu espaço de criação — onde ideias viram interfaces.',p1:'Estou construindo minha jornada em desenvolvimento web com curiosidade, prática e atenção às pessoas que usam o produto.',p2:'Gosto de partir de problemas do mundo real e organizar soluções simples, úteis e visualmente consistentes. Cada projeto é uma oportunidade de aprender um pouco mais sobre produto, código e colaboração.',link:'Conheça minha jornada'},
    projects:{eyebrow:'03 — PROJETOS SELECIONADOS',title:'Aprender é melhor<br />quando se <em>constrói.</em>',intro:'Projetos que transformam requisitos em experiências úteis, acessíveis e bem organizadas.'},
    journey:{eyebrow:'JORNADA',title:'Em constante<br /><em>construção.</em>'},skills:{eyebrow:'05 — FERRAMENTAS',title:'Tecnologia a serviço<br />da <em>experiência.</em>'},
    contact:{eyebrow:'06 — CONTATO',title:'Vamos criar algo<br /><em>relevante?</em>',copy:'Aberto a oportunidades, colaborações e boas conversas.'},footer:'Feito com intenção.',
    projectsData:[{title:'Sistema de Gestão do Futebol Infantil',description:'Uma plataforma para apoiar a organização de atletas, treinos, presença, comunicados e relatórios de um programa municipal.',tech:['HTML5','CSS3','JavaScript','Chart.js','localStorage'],link:'Ver no GitHub',url:'https://github.com/carlosrenatom'},{title:'Laboratório de Desenvolvimento',description:'Uma coleção em evolução de estudos, interfaces e soluções práticas enquanto aprofundo meus fundamentos em desenvolvimento web.',tech:['Em construção','Web'],link:'Explorar GitHub',url:'https://github.com/carlosrenatom'}],
    timeline:[['2025 — agora','Desenvolvimento web em prática','Construção de interfaces e aplicações para transformar aprendizado técnico em entregas concretas.'],['2025','Projeto de extensão','Desenvolvimento de uma solução de gestão para o programa municipal de futebol infantil de Balneário Arroio do Silva.'],['Próximo passo','Mais projetos, mais impacto','Aprofundar conhecimentos e colaborar em projetos que resolvam problemas reais.']],
    skills:[['Fundamentos','HTML5, CSS3, JavaScript'],['Interfaces','Design responsivo, UX, acessibilidade'],['Dados e produto','localStorage, formulários, dashboards'],['Visualização','Chart.js, dados e relatórios'],['Fluxo de trabalho','Git, GitHub, VS Code'],['Em evolução','React, APIs, desenvolvimento full stack']]
  },
  en: {
    skip:'Skip to content', nav:{about:'About',projects:'Projects',journey:'Journey',skills:'Skills',contact:'Contact'},
    hero:{availability:'Open to opportunities',eyebrow:'01 — PORTFOLIO / 2026',title:'Building <em>clear</em> and functional digital experiences.',copy:'I am Carlos Renato, a developer in training. I turn ideas and real needs into interfaces that make sense to people.',projects:'Explore projects',email:'Let’s talk',scroll:'Scroll to discover'},
    about:{eyebrow:'ABOUT ME',title:'Code with intention.<br /><em>Learning</em> in motion.',caption:'My creative space — where ideas become interfaces.',p1:'I am building my web development journey with curiosity, practice, and attention to the people who use the product.',p2:'I enjoy starting from real-world problems and organizing simple, useful, and visually consistent solutions. Every project is an opportunity to learn more about product, code, and collaboration.',link:'Discover my journey'},
    projects:{eyebrow:'03 — SELECTED PROJECTS',title:'Learning is better<br />when you <em>build.</em>',intro:'Projects that turn requirements into useful, accessible, and well-organized experiences.'},
    journey:{eyebrow:'JOURNEY',title:'Always under<br /><em>construction.</em>'},skills:{eyebrow:'05 — TOOLS',title:'Technology serving<br />the <em>experience.</em>'},
    contact:{eyebrow:'06 — CONTACT',title:'Shall we create<br />something <em>meaningful?</em>',copy:'Open to opportunities, collaborations, and good conversations.'},footer:'Made with intention.',
    projectsData:[{title:'Youth Football Management System',description:'A platform that supports the organization of athletes, training sessions, attendance, announcements, and reports for a municipal program.',tech:['HTML5','CSS3','JavaScript','Chart.js','localStorage'],link:'View on GitHub',url:'https://github.com/carlosrenatom'},{title:'Development Lab',description:'An evolving collection of studies, interfaces, and practical solutions as I deepen my web development foundations.',tech:['In progress','Web'],link:'Explore GitHub',url:'https://github.com/carlosrenatom'}],
    timeline:[['2025 — now','Web development in practice','Building interfaces and applications to turn technical learning into tangible delivery.'],['2025','Community project','Developed a management solution for the municipal youth football program in Balneário Arroio do Silva.'],['Next step','More projects, more impact','Deepening my knowledge and collaborating on projects that solve real problems.']],
    skills:[['Foundations','HTML5, CSS3, JavaScript'],['Interfaces','Responsive design, UX, accessibility'],['Data and product','localStorage, forms, dashboards'],['Visualization','Chart.js, data and reports'],['Workflow','Git, GitHub, VS Code'],['Growing into','React, APIs, full-stack development']]
  }
};

const languageButton=document.querySelector('.language-toggle');
let language=localStorage.getItem('portfolio-language')||'pt';
const setLanguage=(lang)=>{language=lang;localStorage.setItem('portfolio-language',lang);document.documentElement.lang=lang==='pt'?'pt-BR':'en';const data=content[lang];document.querySelectorAll('[data-i18n]').forEach((el)=>{const value=el.dataset.i18n.split('.').reduce((obj,key)=>obj[key],data);el.textContent=value});document.querySelectorAll('[data-i18n-html]').forEach((el)=>{const value=el.dataset.i18nHtml.split('.').reduce((obj,key)=>obj[key],data);el.innerHTML=value});languageButton.querySelectorAll('span').forEach((el)=>el.classList.toggle('active',el.textContent.toLowerCase()===lang));languageButton.setAttribute('aria-label',lang==='pt'?'Mudar idioma para inglês':'Change language to Portuguese');renderCollections(data)};
function renderCollections(data){document.getElementById('project-list').innerHTML=data.projectsData.map((p,index)=>`<article class="project reveal"><span class="project-index">0${index+1}</span><div><h3>${p.title}</h3><p>${p.description}</p></div><div class="project-tech">${p.tech.map((tag)=>`<span>${tag}</span>`).join('')}</div><a class="project-link" href="${p.url}" target="_blank" rel="noreferrer">${p.link} ↗</a></article>`).join('');document.getElementById('timeline').innerHTML=data.timeline.map(([date,title,description])=>`<li class="reveal"><time>${date}</time><h3>${title}</h3><p>${description}</p></li>`).join('');document.getElementById('skill-grid').innerHTML=data.skills.map(([title,items])=>`<article class="skill-group reveal"><h3>${title}</h3><p>${items}</p></article>`).join('');observeReveals()}
function observeReveals(){const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal:not(.is-visible)').forEach((el)=>observer.observe(el))}
languageButton.addEventListener('click',()=>setLanguage(language==='pt'?'en':'pt'));document.getElementById('year').textContent=new Date().getFullYear();setLanguage(language);observeReveals();
