const content = {
  pt: {
    skip:'Pular para o conteúdo', nav:{about:'Sobre',projects:'Projetos',journey:'Jornada',skills:'Skills',contact:'Contato'},
    hero:{availability:'Disponível para oportunidades',eyebrow:'01 — PORTFÓLIO / 2026',title:'Construindo experiências digitais <em>claras</em> e funcionais.',copy:'Sou Carlos Renato, desenvolvedor web e software. Transformo ideias e necessidades reais em interfaces e sistemas que fazem sentido para as pessoas.',projects:'Explorar projetos',email:'Vamos conversar',scroll:'Role para descobrir'},
    about:{eyebrow:'SOBRE MIM',title:'Código com intenção.<br /><em>Aprendizado</em> em movimento.',caption:'Meu espaço de criação — onde ideias viram interfaces.',p1:'Sou desenvolvedor web e software, com experiência em interfaces, integrações com APIs e evolução de sistemas. Atualmente atuo na Izzyblue Sistemas e também desenvolvo projetos freelance.',p2:'Trago uma base que passa por suporte técnico, contato direto com usuários e desenvolvimento de produtos como a plataforma Acartoex. Gosto de transformar necessidades reais em soluções simples, responsivas e bem organizadas.',link:'Conheça minha jornada'},
    projects:{eyebrow:'03 — PROJETOS SELECIONADOS',title:'Aprender é melhor<br />quando se <em>constrói.</em>',intro:'Projetos que transformam requisitos em experiências úteis, acessíveis e bem organizadas.'},
    journey:{eyebrow:'JORNADA',title:'Em constante<br /><em>construção.</em>',educationLabel:'FORMAÇÃO EM CURSO',education:'Bacharelado em Engenharia de Software — UNOPAR, 2022–2027.'},skills:{eyebrow:'05 — FERRAMENTAS',title:'Tecnologia a serviço<br />da <em>experiência.</em>'},
    contact:{eyebrow:'06 — CONTATO',title:'Vamos criar algo<br /><em>relevante?</em>',copy:'Aberto a oportunidades, colaborações e boas conversas.',copyEmail:'Copiar e-mail',copied:'E-mail copiado.'},footer:'Feito com intenção.',
    projectsData:[{title:'Acartoex',description:'Site institucional e plataforma de gestão para uma empresa de drywall e gesso acartonado, com áreas técnica e administrativa.',tech:['React','TypeScript','FastAPI','MySQL'],link:'Visitar site',url:'https://acartoex.com.br/'},{title:'Sistema de Gestão do Futebol Infantil',description:'Uma plataforma para apoiar a organização de atletas, treinos, presença, comunicados e relatórios de um programa municipal.',tech:['HTML5','CSS3','JavaScript','Chart.js','localStorage'],links:[{label:'Visitar site',url:'https://treinoinfantil.netlify.app/'},{label:'Ver no GitHub',url:'https://github.com/carlosrenatom/sistema-gestao-futebol-infantil'}]},{title:'Laboratório de Desenvolvimento',description:'Uma coleção em evolução de estudos, interfaces e soluções práticas enquanto aprofundo meus fundamentos em desenvolvimento web.',tech:['Em construção','Web'],link:'Explorar GitHub',url:'https://github.com/carlosrenatom'}],
    timeline:[['2026 — agora','Desenvolvedor Web freelance','Desenvolvimento de sites e sistemas responsivos com dashboards, autenticação, integração de backend e organização de informações. A Acartoex é um dos projetos em destaque.'],['2025 — agora','Desenvolvedor Web e Software — Izzyblue Sistemas','Desenvolvimento e manutenção de interfaces web, implementação de funcionalidades, correção de bugs, integrações com APIs e banco de dados, e apoio à evolução de sistemas internos.'],['2024 — 2025','Suporte ao cliente — Hello Sistemas','Atendimento técnico, diagnóstico de problemas e acompanhamento de chamados. Essa experiência fortaleceu a escuta de usuários e a tradução de demandas em soluções práticas.'],['2022 — 2023','Agente Censitário Supervisor — IBGE','Supervisão de campo, organização de dados, apoio à equipe e atenção à qualidade das informações durante o Censo Demográfico.'],['2015 — 2022','Técnico em Informática freelance','Suporte a usuários, manutenção de computadores, configuração de sistemas e resolução de problemas técnicos para clientes.']],
    skillsData:[['Frontend','React, TypeScript, Vite, Tailwind CSS'],['Backend e dados','Python, FastAPI, JWT, MySQL, APIs REST'],['Interfaces','HTML5, CSS3, JavaScript, responsividade e usabilidade'],['Sistemas','Manutenção, correção de bugs, demandas internas e Delphi'],['Produto e relatórios','Dashboards, formulários, Chart.js e geração de PDFs'],['Fluxo de trabalho','Git, GitHub, VS Code e colaboração com equipes']]
  },
  en: {
    skip:'Skip to content', nav:{about:'About',projects:'Projects',journey:'Journey',skills:'Skills',contact:'Contact'},
    hero:{availability:'Open to opportunities',eyebrow:'01 — PORTFOLIO / 2026',title:'Building <em>clear</em> and functional digital experiences.',copy:'I am Carlos Renato, a web and software developer. I turn ideas and real needs into interfaces and systems that make sense to people.',projects:'Explore projects',email:'Let’s talk',scroll:'Scroll to discover'},
    about:{eyebrow:'ABOUT ME',title:'Code with intention.<br /><em>Learning</em> in motion.',caption:'My creative space — where ideas become interfaces.',p1:'I am a web and software developer with experience in interfaces, API integrations, and system evolution. I currently work at Izzyblue Sistemas while also building freelance projects.',p2:'My background combines technical support, direct contact with users, and products such as the Acartoex platform. I enjoy turning real needs into simple, responsive, and well-organized solutions.',link:'Discover my journey'},
    projects:{eyebrow:'03 — SELECTED PROJECTS',title:'Learning is better<br />when you <em>build.</em>',intro:'Projects that turn requirements into useful, accessible, and well-organized experiences.'},
    journey:{eyebrow:'JOURNEY',title:'Always under<br /><em>construction.</em>',educationLabel:'EDUCATION IN PROGRESS',education:'Bachelor’s degree in Software Engineering — UNOPAR, 2022–2027.'},skills:{eyebrow:'05 — TOOLS',title:'Technology serving<br />the <em>experience.</em>'},
    contact:{eyebrow:'06 — CONTACT',title:'Shall we create<br />something <em>meaningful?</em>',copy:'Open to opportunities, collaborations, and good conversations.',copyEmail:'Copy email',copied:'Email copied.'},footer:'Made with intention.',
    projectsData:[{title:'Acartoex',description:'An institutional website and management platform for a drywall and gypsum board company, with technical and administrative areas.',tech:['React','TypeScript','FastAPI','MySQL'],link:'Visit site',url:'https://acartoex.com.br/'},{title:'Youth Football Management System',description:'A platform that supports the organization of athletes, training sessions, attendance, announcements, and reports for a municipal program.',tech:['HTML5','CSS3','JavaScript','Chart.js','localStorage'],links:[{label:'Visit site',url:'https://treinoinfantil.netlify.app/'},{label:'View on GitHub',url:'https://github.com/carlosrenatom/sistema-gestao-futebol-infantil'}]},{title:'Development Lab',description:'An evolving collection of studies, interfaces, and practical solutions as I deepen my web development foundations.',tech:['In progress','Web'],link:'Explore GitHub',url:'https://github.com/carlosrenatom'}],
    timeline:[['2026 — now','Freelance Web Developer','Building responsive websites and systems with dashboards, authentication, backend integrations, and clear information architecture. Acartoex is a featured project.'],['2025 — now','Web and Software Developer — Izzyblue Sistemas','Developing and maintaining web interfaces, shipping features, fixing bugs, integrating APIs and databases, and helping internal systems evolve.'],['2024 — 2025','Customer Support Assistant — Hello Sistemas','Provided technical support, investigated issues, and tracked requests. This experience sharpened my ability to listen to users and turn needs into practical solutions.'],['2022 — 2023','Census Field Supervisor — IBGE','Coordinated field activities, organized data, supported the team, and upheld information quality during the Demographic Census.'],['2015 — 2022','Freelance IT Technician','Supported users, maintained computers, configured systems, and solved technical issues directly for clients.']],
    skillsData:[['Frontend','React, TypeScript, Vite, Tailwind CSS'],['Backend and data','Python, FastAPI, JWT, MySQL, REST APIs'],['Interfaces','HTML5, CSS3, JavaScript, responsiveness, and usability'],['Systems','Maintenance, bug fixing, internal demands, and Delphi'],['Product and reports','Dashboards, forms, Chart.js, and PDF generation'],['Workflow','Git, GitHub, VS Code, and team collaboration']]
  }
};

const languageButton=document.querySelector('.language-toggle');
let language=localStorage.getItem('portfolio-language')||'pt';
const setLanguage=(lang)=>{language=lang;localStorage.setItem('portfolio-language',lang);document.documentElement.lang=lang==='pt'?'pt-BR':'en';const data=content[lang];document.querySelectorAll('[data-i18n]').forEach((el)=>{const value=el.dataset.i18n.split('.').reduce((obj,key)=>obj[key],data);el.textContent=value});document.querySelectorAll('[data-i18n-html]').forEach((el)=>{const value=el.dataset.i18nHtml.split('.').reduce((obj,key)=>obj[key],data);el.innerHTML=value});languageButton.querySelectorAll('span').forEach((el)=>el.classList.toggle('active',el.textContent.toLowerCase()===lang));languageButton.setAttribute('aria-label',lang==='pt'?'Mudar idioma para inglês':'Change language to Portuguese');renderCollections(data)};
function renderCollections(data){document.getElementById('project-list').innerHTML=data.projectsData.map((p,index)=>`<article class="project reveal"><span class="project-index">0${index+1}</span><div><h3>${p.title}</h3><p>${p.description}</p></div><div class="project-tech">${p.tech.map((tag)=>`<span>${tag}</span>`).join('')}</div><div class="project-links">${(p.links||[{label:p.link,url:p.url}]).map((link)=>`<a class="project-link" href="${link.url}" target="_blank" rel="noreferrer">${link.label} ↗</a>`).join('')}</div></article>`).join('');document.getElementById('timeline').innerHTML=data.timeline.map(([date,title,description])=>`<li class="reveal"><time>${date}</time><h3>${title}</h3><p>${description}</p></li>`).join('');document.getElementById('skill-grid').innerHTML=data.skillsData.map(([title,items])=>`<article class="skill-group reveal"><h3>${title}</h3><p>${items}</p></article>`).join('');observeReveals()}
function observeReveals(){const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal:not(.is-visible)').forEach((el)=>observer.observe(el))}
languageButton.addEventListener('click',()=>setLanguage(language==='pt'?'en':'pt'));document.getElementById('year').textContent=new Date().getFullYear();setLanguage(language);observeReveals();const emailCopyButton=document.querySelector('.email-copy');const emailFeedback=document.querySelector('.email-feedback');emailCopyButton.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(emailCopyButton.dataset.email);emailFeedback.textContent=content[language].contact.copied}catch{emailFeedback.textContent=emailCopyButton.dataset.email}});
